In [ ]:
%pip install keras_tuner

Requirement already satisfied: keras_tuner in /usr/local/lib/python3.13/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (1.83.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras_tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras_tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras_tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras_tuner) (0.1.2)

In [ ]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import keras_tuner as kt

from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("/wdbc.data",header = None)

In [ ]:
columns = [
    "id", "diagnosis",

    "radius_mean", "texture_mean", "perimeter_mean",
    "area_mean", "smoothness_mean", "compactness_mean",
    "concavity_mean", "concave_points_mean",
    "symmetry_mean", "fractal_dimension_mean",

    "radius_se", "texture_se", "perimeter_se",
    "area_se", "smoothness_se", "compactness_se",
    "concavity_se", "concave_points_se",
    "symmetry_se", "fractal_dimension_se",

    "radius_worst", "texture_worst", "perimeter_worst",
    "area_worst", "smoothness_worst", "compactness_worst",
    "concavity_worst", "concave_points_worst",
    "symmetry_worst", "fractal_dimension_worst"
]

In [ ]:
df.columns = columns

In [ ]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
df.isna().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave_points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave_points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave_points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [ ]:
df["diagnosis"].value_counts()   #B-Benign M - Malignant

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
X = df.drop(columns = "diagnosis",axis = 1)

In [ ]:
X = df.drop(columns=["id", "diagnosis"], axis=1)

In [ ]:
y = df["diagnosis"].map({'M': 1, 'B': 0})

In [ ]:
X = df.drop(columns=["id", "diagnosis"], axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(10,activation = "relu",input_shape = (30,)))
model.add(Dense(1,activation = "sigmoid"))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer = "adam",loss="binary_crossentropy",metrics = ["accuracy"])

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.3269 - loss: 7.8525 - val_accuracy: 0.4615 - val_loss: 5.8946
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2830 - loss: 3.7919 - val_accuracy: 0.2418 - val_loss: 2.4136
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4560 - loss: 2.0958 - val_accuracy: 0.3846 - val_loss: 1.3568
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4698 - loss: 1.2086 - val_accuracy: 0.6703 - val_loss: 0.7430
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7857 - loss: 0.6465 - val_accuracy: 0.7033 - val_loss: 0.5160
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8159 - loss: 0.5827 - val_accuracy: 0.8791 - val_loss: 0.3220
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8764 - loss: 0.4255 - val_accuracy: 0.8681 - val_loss: 0.3124
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8709 - loss: 0.3742 - val_accuracy: 0.8352 - val_loss: 0.4777
Epoch 9/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8874 - loss: 0.3564 - val_accuracy: 0.8681 - val_loss: 0.3005
Epoch 10/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8984 - loss: 0.3043 - val_accuracy: 0.8571 - val_loss: 0.3110
Epoch 11/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8956 - loss: 0.2997 - val_accuracy: 0.9121 - val_loss: 0.3054
Epoch 12/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8984 - loss: 0.2839 - val_accuracy: 0.8901 - val_loss: 0.2589
Epoch 13/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9011 - loss: 0.2697 - val_accuracy: 0.8901 - val_loss: 0.2422
Epoch 14/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9093 - loss: 0.2628 - val_accuracy: 0.8901 - val_loss: 0.2850
Epoch 15/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9066 - loss: 0.2919 - val_accuracy: 0.8901 - val_loss: 0.2444
Epoch 16/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9121 - loss: 0.2724 - val_accuracy: 0.8901 - val_loss: 0.2285
Epoch 17/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9093 - loss: 0.2423 - val_accuracy: 0.9011 - val_loss: 0.2326
Epoch 18/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9121 - loss: 0.2487 - val_accuracy: 0.8681 - val_loss: 0.3624
Epoch 19/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9038 - loss: 0.2831 - val_accuracy: 0.9121 - val_loss: 0.2325
Epoch 20/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9286 - loss: 0.2176 - val_accuracy: 0.8681 - val_loss: 0.2521
Epoch 21/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9038 - loss: 0.2383 - val_accuracy: 0.8571 - val_loss: 0.2845
Epoch 22/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9093 - loss: 0.2271 - val_accuracy: 0.8901 - val_loss: 0.2249
Epoch 23/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9176 - loss: 0.1937 - val_accuracy: 0.8901 - val_loss: 0.2227
Epoch 24/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9203 - loss: 0.2037 - val_accuracy: 0.8681 - val_loss: 0.2656
Epoch 25/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9176 - loss: 0.2001 - val_accuracy: 0.8791 - val_loss: 0.2270
Epoch 26/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9286 - loss: 0.1872 - val_accuracy: 0.9231 - val_loss: 0.2210
Epoch 27/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9231 - loss: 0.1867 - val_accuracy: 0.9341 - val_loss: 0.2201
Epoch 28/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9396 - loss: 0.1695 - val_accuracy: 0.8681 - val_loss: 0.2613
Epoch 29/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9396 - loss: 0.1639 - val_accuracy: 0.9231 - val_loss: 0.2126
Epoch 30/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9231 - loss: 0.1862 - val_accuracy: 0.9231 - val_loss: 0.2163
Epoch 31/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9148 - loss: 0.1912 - val_accuracy: 0.9231 - val_loss: 0.2369
Epoch 32/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9093 - loss: 0.2139 - val_accuracy: 0.9231 - val_loss: 0.2415
Epoch 33/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9038 - loss: 0.2204 - val_accuracy: 0.8791 - val_loss: 0.3428
Epoch 34/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9038 - loss: 0.2303 - val_accuracy: 0.8791 - val_loss: 0.3297
Epoch 35/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9231 - loss: 0.2219 - val_accuracy: 0.9231 - val_loss: 0.1984
Epoch 36/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9148 - loss: 0.2085 - val_accuracy: 0.9231 - val_loss: 0.2227
Epoch 37/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9121 - loss: 0.2149 - val_accuracy: 0.9231 - val_loss: 0.2137
Epoch 38/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9066 - loss: 0.2467 - val_accuracy: 0.8791 - val_loss: 0.3394
Epoch 39/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9258 - loss: 0.1792 - val_accuracy: 0.9121 - val_loss: 0.2405
Epoch 40/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9258 - loss: 0.1694 - val_accuracy: 0.9231 - val_loss: 0.1970
Epoch 41/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9396 - loss: 0.1559 - val_accuracy: 0.9231 - val_loss: 0.2258
Epoch 42/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9396 - loss: 0.1660 - val_accuracy: 0.9121 - val_loss: 0.1954
Epoch 43/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9368 - loss: 0.1603 - val_accuracy: 0.9121 - val_loss: 0.2032
Epoch 44/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9258 - loss: 0.1622 - val_accuracy: 0.9121 - val_loss: 0.1907
Epoch 45/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9451 - loss: 0.1596 - val_accuracy: 0.9011 - val_loss: 0.2385
Epoch 46/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9203 - loss: 0.1727 - val_accuracy: 0.9231 - val_loss: 0.2067
Epoch 47/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9176 - loss: 0.1793 - val_accuracy: 0.8901 - val_loss: 0.2995
Epoch 48/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9505 - loss: 0.1559 - val_accuracy: 0.9231 - val_loss: 0.1885
Epoch 49/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9423 - loss: 0.1527 - val_accuracy: 0.8901 - val_loss: 0.2587
Epoch 50/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9451 - loss: 0.1690 - val_accuracy: 0.9231 - val_loss: 0.1920

In [ ]:
def build_model(hp):

    model = Sequential()

    model.add(
        Dense(
            units=hp.Int("units_1", min_value=16,
                         max_value=64, step=16),
            activation="relu",
            input_shape=(30,)
        )
    )



    model.add(Dense(1, activation="sigmoid"))

    model.compile(
        optimizer=Adam(
            learning_rate=hp.Choice(
                "learning_rate",
                values=[0.01, 0.001, 0.0001]
            )
        ),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    return model

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective="val_accuracy",
    max_trials=10,
    executions_per_trial=1,
    directory="ann_tuning",
    project_name="breast_cancer"
)

Reloading Tuner from ann_tuning/breast_cancer/tuner0.json

In [ ]:
tuner.search(X_train,y_train,epochs = 30,batch_size = 32,validation_split = 0.2)

In [ ]:
best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]

best_model = tuner.hypermodel.build(best_hp)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
best_hp

In [ ]:
best_model

In [ ]:
history = best_model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.5962 - loss: 13.9356 - val_accuracy: 0.7363 - val_loss: 13.5230
Epoch 2/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7775 - loss: 4.9115 - val_accuracy: 0.8022 - val_loss: 6.6303
Epoch 3/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8462 - loss: 1.8794 - val_accuracy: 0.8022 - val_loss: 4.8774
Epoch 4/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8269 - loss: 2.8975 - val_accuracy: 0.7912 - val_loss: 5.6913
Epoch 5/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8132 - loss: 2.9030 - val_accuracy: 0.8132 - val_loss: 4.9902
Epoch 6/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8187 - loss: 2.6219 - val_accuracy: 0.8242 - val_loss: 3.7374
Epoch 7/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8654 - loss: 1.4657 - val_accuracy: 0.8681 - val_loss: 2.4480
Epoch 8/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9038 - loss: 0.6933 - val_accuracy: 0.8681 - val_loss: 0.7581
Epoch 9/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8956 - loss: 0.6932 - val_accuracy: 0.7692 - val_loss: 1.4613
Epoch 10/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8874 - loss: 0.7003 - val_accuracy: 0.9011 - val_loss: 0.8147
Epoch 11/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8901 - loss: 0.7261 - val_accuracy: 0.8352 - val_loss: 1.4633
Epoch 12/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8984 - loss: 0.6157 - val_accuracy: 0.9011 - val_loss: 0.5492
Epoch 13/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8929 - loss: 0.4816 - val_accuracy: 0.9121 - val_loss: 0.4594
Epoch 14/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9038 - loss: 0.5246 - val_accuracy: 0.8022 - val_loss: 0.9080
Epoch 15/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8929 - loss: 0.5028 - val_accuracy: 0.9121 - val_loss: 0.5092
Epoch 16/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9121 - loss: 0.4724 - val_accuracy: 0.7033 - val_loss: 1.9878
Epoch 17/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8654 - loss: 0.9798 - val_accuracy: 0.8901 - val_loss: 0.7045
Epoch 18/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8764 - loss: 0.6606 - val_accuracy: 0.9121 - val_loss: 0.5615
Epoch 19/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9121 - loss: 0.5258 - val_accuracy: 0.8242 - val_loss: 1.6093
Epoch 20/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8874 - loss: 0.5240 - val_accuracy: 0.8462 - val_loss: 0.8520
Epoch 21/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9203 - loss: 0.4126 - val_accuracy: 0.9011 - val_loss: 0.4045
Epoch 22/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9258 - loss: 0.2859 - val_accuracy: 0.8462 - val_loss: 0.7143
Epoch 23/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9011 - loss: 0.6367 - val_accuracy: 0.8901 - val_loss: 0.6131
Epoch 24/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8901 - loss: 0.6597 - val_accuracy: 0.8901 - val_loss: 0.3661
Epoch 25/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8819 - loss: 0.7183 - val_accuracy: 0.9121 - val_loss: 0.3879
Epoch 26/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8874 - loss: 0.5785 - val_accuracy: 0.8901 - val_loss: 0.6305
Epoch 27/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9093 - loss: 0.5116 - val_accuracy: 0.8791 - val_loss: 0.6356
Epoch 28/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9121 - loss: 0.2759 - val_accuracy: 0.9011 - val_loss: 0.4489
Epoch 29/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9341 - loss: 0.2728 - val_accuracy: 0.9011 - val_loss: 0.4065
Epoch 30/30
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8874 - loss: 0.5797 - val_accuracy: 0.8242 - val_loss: 1.5734

In [ ]:
print("Tuned Model Evaluation:")

loss, acc = best_model.evaluate(X_train, y_train, verbose=0)

print("Train Accuracy:", acc)
print("Train Accuracy (%):", acc * 100)

Tuned Model Evaluation:
Train Accuracy: 0.8505494594573975
Train Accuracy (%): 85.05494594573975

In [ ]:
print("Tuned Model Evaluation:")

loss, acc = best_model.evaluate(X_test, y_test, verbose=0)

print("Test Accuracy:", acc)
print("Test Accuracy (%):", acc * 100)

Tuned Model Evaluation:
Test Accuracy: 0.9122806787490845
Test Accuracy (%): 91.22806787490845

In [ ]:
train_loss, train_acc = best_model.evaluate(
    X_train, y_train, verbose=0
)

test_loss, test_acc = best_model.evaluate(
    X_test, y_test, verbose=0
)

print(f"Train Accuracy: {train_acc * 100:.2f}%")
print(f"Test Accuracy: {test_acc * 100:.2f}%")

Train Accuracy: 85.05%
Test Accuracy: 91.23%

In [ ]:
print(best_hp.values)

{'units_1': 32, 'learning_rate': 0.01}

In [ ]:
train_loss

1.1716580390930176

In [ ]:
test_loss

0.8303115963935852