In [1]:
%pip install keras_tuner

Collecting keras_tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (2.32.4)
Collecting kt-legacy (from keras_tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (1.83.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras_tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras_tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras_tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras_tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras_tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras_tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras_tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.8 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras_tuner
Successfully installed keras_tuner-1.4.8 kt-legacy-1.0.5

In [16]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2


import keras_tuner as tk

In [3]:
housing = fetch_california_housing(as_frame = True)
df = housing.frame
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [4]:
df.isna().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [5]:
X = df.drop('MedHouseVal',axis = 1)
y = df['MedHouseVal']

In [6]:
X_train ,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [7]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

In [8]:
X_test = scaler.transform(X_test)

In [9]:
model = Sequential([Dense(4,activation = "relu",input_shape = (8,)),
                   Dense(1,activation = "linear")])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [10]:
model.compile(optimizer = Adam(learning_rate = 0.001),loss = "mse",metrics = ["mae"])

In [11]:
model.fit(X_train,y_train,epochs = 100,validation_split = 0.2)

Epoch 1/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 2.4674 - mae: 1.1804 - val_loss: 1.3217 - val_mae: 0.8309
Epoch 2/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.9703 - mae: 0.7024 - val_loss: 0.8056 - val_mae: 0.6438
Epoch 3/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.6862 - mae: 0.5922 - val_loss: 0.6436 - val_mae: 0.5754
Epoch 4/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.5610 - mae: 0.5406 - val_loss: 0.5527 - val_mae: 0.5375
Epoch 5/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - loss: 0.4947 - mae: 0.5089 - val_loss: 0.5125 - val_mae: 0.5177
Epoch 6/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 0.4631 - mae: 0.4922 - val_loss: 0.4919 - val_mae: 0.5015
Epoch 7/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.4479 - mae: 0.4819 - val_loss: 0.4797 - val_mae: 0.4986
Epoch 8/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4374 - mae: 0.4751 - val_loss: 0.4708 - val_mae: 0.4934
Epoch 9/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4299 - mae: 0.4712 - val_loss: 0.4635 - val_mae: 0.4874
Epoch 10/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.4242 - mae: 0.4681 - val_loss: 0.4564 - val_mae: 0.4842
Epoch 11/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.4194 - mae: 0.4647 - val_loss: 0.4538 - val_mae: 0.4812
Epoch 12/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.4161 - mae: 0.4635 - val_loss: 0.4489 - val_mae: 0.4784
Epoch 13/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4124 - mae: 0.4609 - val_loss: 0.4459 - val_mae: 0.4820
Epoch 14/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4098 - mae: 0.4610 - val_loss: 0.4434 - val_mae: 0.4765
Epoch 15/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4063 - mae: 0.4583 - val_loss: 0.4432 - val_mae: 0.4796
Epoch 16/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4050 - mae: 0.4585 - val_loss: 0.4387 - val_mae: 0.4723
Epoch 17/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4019 - mae: 0.4558 - val_loss: 0.4382 - val_mae: 0.4721
Epoch 18/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3995 - mae: 0.4545 - val_loss: 0.4360 - val_mae: 0.4739
Epoch 19/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3975 - mae: 0.4532 - val_loss: 0.4322 - val_mae: 0.4720
Epoch 20/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3960 - mae: 0.4527 - val_loss: 0.4357 - val_mae: 0.4708
Epoch 21/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3942 - mae: 0.4518 - val_loss: 0.4311 - val_mae: 0.4662
Epoch 22/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3917 - mae: 0.4503 - val_loss: 0.4287 - val_mae: 0.4698
Epoch 23/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3896 - mae: 0.4490 - val_loss: 0.4264 - val_mae: 0.4669
Epoch 24/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3878 - mae: 0.4482 - val_loss: 0.4264 - val_mae: 0.4689
Epoch 25/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3855 - mae: 0.4468 - val_loss: 0.4230 - val_mae: 0.4645
Epoch 26/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3830 - mae: 0.4455 - val_loss: 0.4222 - val_mae: 0.4645
Epoch 27/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3810 - mae: 0.4440 - val_loss: 0.4205 - val_mae: 0.4632
Epoch 28/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3795 - mae: 0.4433 - val_loss: 0.4188 - val_mae: 0.4647
Epoch 29/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3789 - mae: 0.4413 - val_loss: 0.4177 - val_mae: 0.4609
Epoch 30/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3765 - mae: 0.4398 - val_loss: 0.4133 - val_mae: 0.4602
Epoch 31/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3738 - mae: 0.4387 - val_loss: 0.4132 - val_mae: 0.4564
Epoch 32/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3733 - mae: 0.4372 - val_loss: 0.4092 - val_mae: 0.4551
Epoch 33/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3719 - mae: 0.4361 - val_loss: 0.4116 - val_mae: 0.4565
Epoch 34/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3716 - mae: 0.4357 - val_loss: 0.4080 - val_mae: 0.4557
Epoch 35/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3696 - mae: 0.4345 - val_loss: 0.4066 - val_mae: 0.4559
Epoch 36/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3688 - mae: 0.4344 - val_loss: 0.4057 - val_mae: 0.4508
Epoch 37/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3697 - mae: 0.4333 - val_loss: 0.4071 - val_mae: 0.4528
Epoch 38/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3670 - mae: 0.4325 - val_loss: 0.4041 - val_mae: 0.4511
Epoch 39/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3664 - mae: 0.4318 - val_loss: 0.4057 - val_mae: 0.4536
Epoch 40/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3659 - mae: 0.4310 - val_loss: 0.4027 - val_mae: 0.4507
Epoch 41/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3657 - mae: 0.4317 - val_loss: 0.4030 - val_mae: 0.4497
Epoch 42/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3656 - mae: 0.4305 - val_loss: 0.4030 - val_mae: 0.4507
Epoch 43/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3654 - mae: 0.4303 - val_loss: 0.4033 - val_mae: 0.4484
Epoch 44/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3650 - mae: 0.4305 - val_loss: 0.4018 - val_mae: 0.4489
Epoch 45/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.3659 - mae: 0.4301 - val_loss: 0.4038 - val_mae: 0.4507
Epoch 46/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3640 - mae: 0.4298 - val_loss: 0.4032 - val_mae: 0.4496
Epoch 47/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3636 - mae: 0.4294 - val_loss: 0.4030 - val_mae: 0.4475
Epoch 48/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3635 - mae: 0.4288 - val_loss: 0.4017 - val_mae: 0.4485
Epoch 49/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3636 - mae: 0.4292 - val_loss: 0.4028 - val_mae: 0.4497
Epoch 50/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3629 - mae: 0.4289 - val_loss: 0.4025 - val_mae: 0.4522
Epoch 51/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3629 - mae: 0.4288 - val_loss: 0.4012 - val_mae: 0.4499
Epoch 52/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3632 - mae: 0.4282 - val_loss: 0.4027 - val_mae: 0.4508
Epoch 53/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3628 - mae: 0.4284 - val_loss: 0.4018 - val_mae: 0.4510
Epoch 54/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3636 - mae: 0.4289 - val_loss: 0.4004 - val_mae: 0.4474
Epoch 55/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3621 - mae: 0.4279 - val_loss: 0.4012 - val_mae: 0.4493
Epoch 56/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3620 - mae: 0.4271 - val_loss: 0.4006 - val_mae: 0.4506
Epoch 57/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3622 - mae: 0.4279 - val_loss: 0.4002 - val_mae: 0.4475
Epoch 58/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3624 - mae: 0.4275 - val_loss: 0.3997 - val_mae: 0.4488
Epoch 59/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3622 - mae: 0.4275 - val_loss: 0.3993 - val_mae: 0.4475
Epoch 60/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3614 - mae: 0.4275 - val_loss: 0.4009 - val_mae: 0.4479
Epoch 61/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3617 - mae: 0.4279 - val_loss: 0.3990 - val_mae: 0.4459
Epoch 62/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3620 - mae: 0.4273 - val_loss: 0.4018 - val_mae: 0.4485
Epoch 63/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3612 - mae: 0.4280 - val_loss: 0.4001 - val_mae: 0.4460
Epoch 64/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3612 - mae: 0.4269 - val_loss: 0.4003 - val_mae: 0.4495
Epoch 65/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.3607 - mae: 0.4272 - val_loss: 0.4033 - val_mae: 0.4520
Epoch 66/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 0.3612 - mae: 0.4274 - val_loss: 0.3993 - val_mae: 0.4474
Epoch 67/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.3608 - mae: 0.4265 - val_loss: 0.3986 - val_mae: 0.4460
Epoch 68/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - loss: 0.3609 - mae: 0.4271 - val_loss: 0.3987 - val_mae: 0.4480
Epoch 69/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 0.3609 - mae: 0.4270 - val_loss: 0.3986 - val_mae: 0.4478
Epoch 70/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.3608 - mae: 0.4264 - val_loss: 0.4000 - val_mae: 0.4494
Epoch 71/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3607 - mae: 0.4273 - val_loss: 0.3984 - val_mae: 0.4463
Epoch 72/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3607 - mae: 0.4266 - val_loss: 0.3986 - val_mae: 0.4462
Epoch 73/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3604 - mae: 0.4265 - val_loss: 0.3986 - val_mae: 0.4452
Epoch 74/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3601 - mae: 0.4267 - val_loss: 0.3977 - val_mae: 0.4444
Epoch 75/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3605 - mae: 0.4262 - val_loss: 0.3991 - val_mae: 0.4503
Epoch 76/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3607 - mae: 0.4265 - val_loss: 0.4036 - val_mae: 0.4480
Epoch 77/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3602 - mae: 0.4260 - val_loss: 0.3980 - val_mae: 0.4470
Epoch 78/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3599 - mae: 0.4262 - val_loss: 0.3979 - val_mae: 0.4455
Epoch 79/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3606 - mae: 0.4265 - val_loss: 0.3971 - val_mae: 0.4460
Epoch 80/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3606 - mae: 0.4269 - val_loss: 0.3986 - val_mae: 0.4451
Epoch 81/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3602 - mae: 0.4258 - val_loss: 0.3972 - val_mae: 0.4460
Epoch 82/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3600 - mae: 0.4263 - val_loss: 0.3975 - val_mae: 0.4443
Epoch 83/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3598 - mae: 0.4261 - val_loss: 0.3987 - val_mae: 0.4448
Epoch 84/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3597 - mae: 0.4260 - val_loss: 0.3969 - val_mae: 0.4455
Epoch 85/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3596 - mae: 0.4260 - val_loss: 0.3971 - val_mae: 0.4461
Epoch 86/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3594 - mae: 0.4260 - val_loss: 0.3979 - val_mae: 0.4477
Epoch 87/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3590 - mae: 0.4259 - val_loss: 0.3967 - val_mae: 0.4439
Epoch 88/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3595 - mae: 0.4262 - val_loss: 0.3970 - val_mae: 0.4443
Epoch 89/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3592 - mae: 0.4257 - val_loss: 0.3973 - val_mae: 0.4466
Epoch 90/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3582 - mae: 0.4253 - val_loss: 0.3979 - val_mae: 0.4476
Epoch 91/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3594 - mae: 0.4261 - val_loss: 0.3977 - val_mae: 0.4460
Epoch 92/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3587 - mae: 0.4256 - val_loss: 0.3964 - val_mae: 0.4434
Epoch 93/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3595 - mae: 0.4261 - val_loss: 0.3991 - val_mae: 0.4449
Epoch 94/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3588 - mae: 0.4259 - val_loss: 0.3958 - val_mae: 0.4440
Epoch 95/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3584 - mae: 0.4256 - val_loss: 0.3961 - val_mae: 0.4442
Epoch 96/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3598 - mae: 0.4254 - val_loss: 0.3979 - val_mae: 0.4491
Epoch 97/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.3591 - mae: 0.4256 - val_loss: 0.3960 - val_mae: 0.4454
Epoch 98/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.3580 - mae: 0.4250 - val_loss: 0.3973 - val_mae: 0.4437
Epoch 99/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3590 - mae: 0.4260 - val_loss: 0.3966 - val_mae: 0.4463
Epoch 100/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3589 - mae: 0.4257 - val_loss: 0.3963 - val_mae: 0.4443

In [12]:
test_loss , test_acc = model.evaluate(X_test,y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3771 - mae: 0.4283

In [13]:
test_acc

0.42834487557411194

In [20]:
def build_model(hp):
  model = Sequential([
      Dense(units = hp.Int("units_1",min_value = 8,max_value = 64 ,step = 8),activation = "relu",input_shape = (8,),kernel_regularizer=l2(0.01)),
      Dense(1,activation = "linear")
  ])

  model.compile(optimizer = Adam(learning_rate = hp.Choice("learning_rate",values=[0.01, 0.001, 0.0001])),loss = "mse",metrics = ["mae"])
  return model

In [21]:
tuner = tk.RandomSearch(
    build_model,
    objective="val_mae",
    max_trials=10,
    executions_per_trial=1,
    directory="ann_tuning",
    project_name="house_price"
)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
model1 = tuner.search(X_train, y_train, epochs=10, validation_split=0.2)
model1

Trial 10 Complete [00h 00m 13s]
val_mae: 0.4649542272090912

Best val_mae So Far: 0.45185840129852295
Total elapsed time: 00h 02m 33s

In [23]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
R² Score: 0.7122568195943997

In [25]:
best_model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [26]:
best_model

In [29]:
y_pred = best_model.evaluate(X_test,y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.4716 - mae: 0.4452

In [32]:
y_pred_best_model = best_model.predict(X_test)
r2 = r2_score(y_test, y_pred_best_model)
print("R² Score for best model:", r2)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
R² Score for best model: 0.667075531835005